import Link from 'next/link';

interface MethodologyFootnotesProps {
  scoringVersion: number;
}

export function MethodologyFootnotes({ scoringVersion }: MethodologyFootnotesProps) {
  return (
    <footer className="border-t border-border py-16">
      <div className="space-y-6">
        <span className="font-[family-name:var(--font-mono)] text-xs uppercase tracking-[0.1em] text-text-tertiary">
          Methodology
        </span>

        <div className="space-y-4 text-sm text-text-secondary leading-relaxed max-w-xl">
          <p>
            Scores are computed from 15 federal data sources using a weighted
            five-layer composite (water 25%, air 25%, proximity 20%, soil 15%,
            EJ 15%). When a layer is unavailable, remaining layers are
            re-weighted proportionally.
          </p>
          <p>
            All recommendations are deterministic — sourced from expert-written
            templates triggered by specific data thresholds, not generated by AI.
            The AI component describes data in plain English; it never
            prescribes actions or makes safety claims.
          </p>
          <p>
            This report aggregates publicly available federal data for
            informational purposes. It is not a substitute for professional
            environmental testing, inspection, or medical advice.
          </p>
        </div>

        <div className="flex items-center gap-4 text-xs text-text-tertiary font-[family-name:var(--font-mono)]">
          <span>Scoring v{scoringVersion}</span>
          <span aria-hidden="true">·</span>
          <Link
            href="/methodology"
            className="underline underline-offset-2 hover:text-text-secondary transition-colors"
          >
            Full methodology
          </Link>
        </div>
      </div>
    </footer>
  );
}
